import { RoomStatus } from '../room/room-status.enum';
import { Room } from '../room/room.model';

export interface Building {
  id: number;
  name: string;
  floors: number[];
  rooms: Record<number, Room[]>;
}

export const buildings: Building[] = [
  {
    id: 1,
    name: 'Building A',
    floors: [1, 2],
    rooms: {
      1: [
        {
          id: 'room-10101',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [
            'https://scontent.fhdy2-1.fna.fbcdn.net/v/t39.30808-6/489926757_979961950941737_2917545348810691037_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=UpRtrs0uTTgQ7kNvwGgV4Nv&_nc_oc=AdkicA5Ok8_lOoGJZ3zx5oMrEZDuJFKA52mFg4GZTXrnPuJc6mWoDfLx5Z-VBN_7i5Q&_nc_zt=23&_nc_ht=scontent.fhdy2-1.fna&_nc_gid=_8VHy_r7f-rwG_cV3jKJhQ&oh=00_AfEYpmaBbTR7azxRB08YNC4vh-Uh5rt3AnYf8tLNmKFALA&oe=68150333',
          ],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10102',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10103',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10104',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10105',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10106',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10107',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10108',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10109',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10110',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10111',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10112',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10113',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10114',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10115',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10116',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10117',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10118',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10119',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 10000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
      ],
      2: [
        {
          id: 'room-10201',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10202',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10203',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10204',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10205',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10206',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10207',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10208',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10209',
          typeId: 'type-b',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10210',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10211',
          typeId: 'type-b',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10212',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10213',
          typeId: 'type-b',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10214',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10215',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10216',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10217',
          typeId: 'type-b',
          status: RoomStatus.Occupied,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10218',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-10219',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 11000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
      ],
    },
  },
  {
    id: 2,
    name: 'Building B',
    floors: [1, 2, 3],
    rooms: {
      1: [
        {
          id: 'room-20101',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20102',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20103',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20104',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20105',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20106',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20107',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20108',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20109',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20110',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20111',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20112',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20113',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20114',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20115',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20116',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20117',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20118',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20119',
          typeId: 'type-a',
          status: RoomStatus.Available,
          price: 8500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
      ],
      2: [
        {
          id: 'room-20201',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 10500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        {
          id: 'room-20202',
          typeId: 'type-a',
          status: RoomStatus.Occupied,
          price: 9500,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
        // ... rest of the rooms with typeId added
      ],
      3: [
        {
          id: 'room-20301',
          typeId: 'type-b',
          status: RoomStatus.Available,
          price: 9000,
          imageUrl: [''],
          virtualTourOverrideUrl: '',
        },
      ],
    },
  },
];
